<?php

declare(strict_types=1);

$finder = (new PhpCsFixer\Finder())
    // Default finder ignores __DIR__ . "/vendor" dir, "hidden" paths (ones starting with a dot) and VCS paths (e.g. .git), and filter only for *.php files.
    ->in(__DIR__)

    // Note that exclude will work only for directories, so if you need to exclude a file, use notPath.
    // ->exclude([
    //     'autogenerated_content',
    //     'tests/fixtures',
    // ])
    // ->notPath([
    //     'dump.php',
    //     'src/exception_file.php',
    // ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony' => true,
        'array_indentation' => true,
        'dir_constant' => true,
        'function_to_constant' => [
            'functions' => ['get_called_class', 'get_class', 'get_class_this', 'php_sapi_name', 'phpversion', 'pi'],
        ],
        'method_chaining_indentation' => true,
        'modernize_types_casting' => true,
        'self_accessor' => true,
        'string_line_ending' => true,
        'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
        'php_unit_strict' => true,
        'php_unit_test_case_static_method_calls' => true,
    ])
    ->setFinder($finder)
;
